### ISSUE TITLE
Refactor tlog-play source creation

### ISSUE THREAD

**Issue by spbnick** [Scribery/tlog#141]
Split tlog-play source creation into functions similarly to what was done to sink creation in lib/rec.c

**Comment by danghai** [comment]
I see you already split source creation into functions : https://github.com/Scribery/tlog/blob/master/lib/tlog/play.c#L279 

It is the same as sink creation in lib/rec.c : 
https://github.com/Scribery/tlog/blob/master/lib/tlog/rec.c#L710

**Comment by spbnick** [comment]
Yeah, it is mostly done, but `tlog_play_create_json_reader` needs to be split into functions per reader type.

**Comment by danghai** [comment]
I already split `tlog_play_create_json_reader` into 3 functions per reader type regarding to `es`, `journal`, and `file`. The name function include: 
a. tlog_play_create_es_json_reader
b. tlog_play_create_journal_json_reader
c. tlog_play_create_file_json_reader

Issue: 
1. I put `es/journal/file` reader conf container into each function. It is different `rec.c` 
2. I already test with tlog-play with `file`, and it works; Unfortunately, I am not sure about test tlog-play with `es` and `journal`.
3. Is it better to use `switch-case` instead of using `if-else` condition?

Please review this commit: 
https://github.com/danghai/tlog/commit/d941e98c27bc7bb291eea1409331a66f51901440
