### ISSUE TITLE
Do not exit tlog-play with "-g end -p" options

### ISSUE THREAD

**Issue by spbnick** [Scribery/tlog#150]
When both `--goto=end` and `--paused` options are specified to tlog-play, it exits after going to the end. Instead it should stay on pause.

**Comment by danghai** [comment]
Hi Nick, I add the `paused` flag in `if (json_object_object_get_ex(conf, "goto", &obj)) {` condition. It will stay on pause instead exiting after going to the end.  Please review the commit: 
if (json_object_object_get_ex(conf, "goto", &obj)) {

**Comment by spbnick** [comment]
Hi Hai, thank you for trying to fix this. However, we still need "goto" to work here, we only need to not exit and stay on pause if we reach the end of recording. See the code which reacts to end-of-recording received from the source and checks for the "goto" being active.

**Comment by danghai** [comment]
For clear, `only` both flag `--goto=end` and `paused` are set at same time (ex: `tlog-play -i tlog.log --goto=END -p`), it should stay on pause instead of exiting? And it normally exits with other options ( Ex: `tlog-play -i tlog.log`: It will play and exit normally after reaching the end of recording). Please review this commit: https://github.com/danghai/tlog/commit/8a45927513fa0650235891cfae3edb19b7f496d4
I handle this by declare one more variable name `init_paused` ( because paused is modified by `space` ), if init_paused is set, it generates `paused` flag.

**Comment by spbnick** [comment]
"goto" works with "paused": it goes to the specified location and stays on pause. Try executing `tlog-play` with `--goto=10` (or some such) and `--paused` and see. It should behave the same for `--goto=end`. I think it should be possible to implement that without introducing a new variable.

**Comment by spbnick** [comment]
Fixed in 1671124b83b67360c392805999112f564128b422. Thanks, Hai!
