### ISSUE TITLE
Tlog-rec override the file. 

### ISSUE THREAD

**Issue by danghai** [Scribery/tlog#175]
Tlog-rec cannot override the file. For example:

`tlog-rec --writer=file --file-path=tlog.log` 

After recording, I want to record with different content in same name: 

`tlog-rec --writer=file --file-path=tlog.log`

New data does not override the old data in `tlog.log`. If you want to keep the old data, it should produce the message `the name file exists`.
One more suggestion: it can append the new data from old data if `tlog-rec` records the same name file

**Comment by spbnick** [comment]
`tlog-rec` appends to the file instead of overriding to keep to the usual approach taken with log files. This primarily originated from the `tlog-rec-session` use case, where the file would be specified in the global configuration and each logged user would write to the same file. If the file would be overwritten that wouldn't be possible. For now you'll need to remove or empty the file yourself if you want to overwrite it with `tlog-rec` or `tlog-rec-session`. We can perhaps add an option to overwrite it later, but for now no real users reported any issue with this and it would be better to keep it simple.

**Comment by spbnick** [comment]
Closing for now, reopen if you disagree. Thank you!
