### ISSUE TITLE
Is it possible to only audit after users elevate to root?

### ISSUE THREAD

**Issue by mikedep333** [Scribery/tlog#226]
Disclaimer: This is a support request / a request for a documentation update. I am filing an issue because http://scribery.github.io does not list any mailing list, only to email an individual developer, which I presume is the greater of 2 evils.

When users login to their regular accounts, we do not need to audit their entire terminal session. Only what they do after they elevate to root with `sudo` or `su` (or perhaps `pkexec`).

Is it possible for tlog to do this? Wouldn't setting root's shell to /usr/bin/tlog-rec-session be very disruptive?

Note that users often run commands like `sudo bash` rather than `sudo -i` or `sudo su`.

**Comment by mikedep333** [comment]
On a test system, I set root's shell to /usr/bin/tlog-rec-session . I did some basic tests, and it seems to work fine.

**Comment by spbnick** [comment]
Hi @mikedep333, I think, in general, security-wise, it doesn't make sense to record the root user with a user-space process such as tlog-rec-session, because disabling the recording would be too easy. Even doing it in the kernel on the same host would be questionable.

If you really want that, then it should work, and if you find a bug in such a setup, then we'll try to fix it. However, it's not the primary use case.

Now, if we only record certain strict set of commands permitted with sudo (e.g. "sudo service httpd restart"), it starts to make more sense, but last time I looked for a way to plug tlog-rec-session in there, I couldn't find a way. Note, however, that sudo has its own recording system. One thing to do in the future, perhaps, would be to make sudo use tlog library to log, but that's far off, if possible.

Otherwise the only more-or-less reliable way to record root would be using a jump host and still recording the whole session.

**Comment by justin-stephenson** [comment]
Closing as this has been answered.
