### ISSUE TITLE
One log per line configuration

### ISSUE THREAD

**Issue by t1nkerer** [Scribery/tlog#232]
Hi,

Would it be possible to have an option to generate 1 log per 1 command?

Currently it will send either after latency setting or when buffer fills.
It would be similar to tacacs.

**Comment by spbnick** [comment]
Hi @t1nkerer, unfortunately tlog works at a low level, where detecting entered commands would be difficult. One approach we could implement is adding an option to flush the buffer when a newline is seen in the input. That would get a message written, but there would be no guarantee that a long command would not get split into two or more messages. Also, you wouldn't get anything meaningful in the log anyway most of the time, because command line input and output would be interspersed with control characters. If you want to see the commands, or rather processes that user executed as opposed to just the "video" of the terminal, look at auditd configuration and logs.
