### ISSUE TITLE
Tlog should give the message when they try to write the same file

### ISSUE THREAD

**Issue by danghai** [Scribery/tlog#277]
Does Tlog should give the message when try to write the same file?
I mean parallel run tlog-rec:
```
tlog-rec --writer=file --file-path=tlog.log
tlog-rec --writer=file --file-path=tlog.log
```

**Comment by justin-stephenson** [comment]
When a separate terminal recording is appended to the same (file writer) log file, the current tlog code only plays back the first recording in the file, restricting the ability to playback any subsequent recordings:
~~~
Message ID is out of order
Failed reading the source at line 2
~~~

I wonder if instead of issuing a warning, we could improve tlog behavior and add a File reader option to tlog-play which allows specifying a recording ID to playback that specific recording. This could alleviate the problem described above.

**Comment by spbnick** [comment]
@justin-stephenson, I think that's something worth exploring.

**Comment by danghai** [comment]
Hi @justin-stephenson , it is a great enhancement for adding a File reader option to tlog-play which allows specifying a recording ID to playback that specific recording
