### ISSUE TITLE
--file-path is not honored in tlog-play

### ISSUE THREAD

**Issue by yuanlinios** [Scribery/tlog#293]
I am following https://access.redhat.com/solutions/4068941 to test export journal to remote host and replay.

```
tlog-play -r journal --file-path=/tmp/mysession.journal -M TLOG_REC=$REC_ID
```
However, I noticed it only works if I put "mysession.journal" under /**var/log/journal**. If there is only "/tmp/mysession.journal", the replay outputs nothing. 

Strace shows me it looks for journals under **/run/log/journal/** and **/var/log/journal/** only, and ignores the path specified in CLI parameter

Environment
* RHEL 8.2
* both tlog v7-2 from yum appstream and tlog v8-2 rpm built from source tar ball have the same issue

**Comment by justin-stephenson** [comment]
@yuanlinios The `--file-path` argument is only intended to work with tlog's "file" writer

You will need to move the exported journal file to /var/log/journal because the "journal" reader only searches the systemd journal system locations. This requirement is also mentioned in RHEL documentation below:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/recording_sessions/deploying-session-recording-getting-started-with-session-recording#exporting-recorded-sessions-to-a-file-deploying-session-recording

I will ask the author of the Knowledge Solution if they can fix it.

**Comment by yuanlinios** [comment]
Makes sense. Thanks
