### ISSUE TITLE
Limiting input collection based on rate

### ISSUE THREAD

**Issue by bec-f** [Scribery/tlog#96]
There's a huge amount of data collected with tlog, which is really thorough, but it fills logs with a lot of "unnecessary" data (i.e. someone holding pagedown on a man page or holding backspace). 
I'm trying to figure out how to limit the collection to "necessary" input by predicting someone is doing something based on rate of typing, similar to in [sudosh2](https://github.com/onyxpoint/sudosh2/blob/master/src/sudosh.c), but I'm not quite sure where to look in tlog to begin. As a kind of starting point for this: where does tlog actually look for and/or collect the data for a process like tlog-rec-session?

**Comment by spbnick** [comment]
Hi @bec-f! Thank you for your report.

Reading terminal data is done in tlog_tty_source_read, in lib/tty_source.c. The data transfer happens in tlog_rec_transfer in lib.rec.c.

I would prefer not to remove any data that we read, and not do any heuristics, if possible. One idea that I have, which can help with this is to store the data in two streams for each direction, in JSON messages. One stream always converted to UTF-8 (if necessary), with control characters removed, aimed at making the messages searchable, and another stream with data as it came in, untouched, for archival and protection of encoding conversion loss, perhaps compressed. Then provide configuration options to turn off one or the other.

What do you think?

Or perhaps we can add input filtering as an option.

**Comment by trevor-vaughan** [comment]
@spbnick and @bec-f This is something that I would also like to see.

The fundamental issue as I see it is that all users, at some point or another, will type something like `cat /dev/urandom <enter>` instead of `cat /dev/urandom | <whatever>` and end up with a couple hundred megs of logs in the `tlog` output that can destroy both your local logging and your network logging.

Or, more realistically `rpm2cpio my.rpm`...oh crap...`rpm2cpio my.rpm | cpio -id`.

This is something that we added to `sudosh2` specifically to limit inadvertent denial of service issues that we saw in practice without this limitation in place.

I would like to 👍 this request and suggest that the rate limiting value be made an option and have the actual feature itself be an option that is disabled by default.

**Comment by spbnick** [comment]
@trevor-vaughan, I think for these cases throttling can work well (#17). The output will simply be slow for the user, and when they see they made a mistake with the redirection they'll be able to interrupt the process before it produces too much output.

In both cases, if any of you wishes to work on this, you're more than welcome. I'll be glad to help you figure it out. For the start, I think either of these can be implemented as a pseudo-sink which accepts another sink as the actual output. Otherwise I should be able to get around to it closer to the autumn.

**Comment by bec-f** [comment]
Hi @spbnick! I've worked on creating the feature for rate-limiting collection in #108!  I have it mostly integrated to the configuration as well, but I've also encountered a few issues I was hoping you could help with. I don't think I understood the m4 parts enough to be able to add the feature to the man pages. The default value for rate ('0.0' so that it is disabled) isn't showing up automatically in the configuration files, and in 'lib/conf_validate.c.m4' I couldn't change "PRId64" to be float for printing errors with validation. I'm not familiar enough with m4 to know how to fix these.  Do you have any suggestions? Thanks so much!

**Comment by spbnick** [comment]
Thanks a lot, @bec-f! Let's discuss this particular change in the pull request. I'll leave a couple comments today and will take a closer look tomorrow.

**Comment by bec-f** [comment]
Okay, great!  I did figure out how to fix the float issue, but the rest still stand. Thanks so much!

**Comment by spbnick** [comment]
Logging rate limiting with both policing (dropping) and shaping (throttling) is implemented now.
